// EXECUTIVE SUMMARY GENERATOR — assembles a narrated report from numbers the
// engine already computed elsewhere (margin, cash calendar, alerts, returns
// ranking, the marketing recommendation). Every line is a template wrapped
// around a real value; nothing here is invented or estimated.

function fmtMoney(v) {
  if (v == null) return "—";
  const neg = v < 0;
  return `${neg ? "−" : ""}$${Math.abs(Math.round(v)).toLocaleString()}`;
}

export function buildExecutiveSummary({ store, rangeLabel, summary, alerts, cashCalendar, marketingRec, returnsRanking }) {
  const profitable = summary.cm3 >= 0;

  const financial = [
    `${store.name} generated ${fmtMoney(summary.revenue)} in revenue over the last ${rangeLabel}.`,
    `After landed costs, shipping, fees, and returns, contribution margin (CM1) was ${fmtMoney(summary.cm1)} (${summary.cm1Pct}% of revenue).`,
    `After ad spend, CM2 was ${fmtMoney(summary.cm2)} (${summary.cm2Pct}% of revenue).`,
    `Net of overhead, CM3 came in at ${fmtMoney(summary.cm3)} (${summary.cm3Pct}%) — ${profitable ? "a healthy, profitable period." : "a net loss this period."}`,
  ];

  const risks = alerts?.length
    ? alerts.map((a) => `${a.title}: ${a.body}`)
    : ["No active alerts this period."];

  const cash = cashCalendar?.items?.length
    ? [
        `${cashCalendar.items.length} product${cashCalendar.items.length === 1 ? "" : "s"} currently need reordering.`,
        `${fmtMoney(cashCalendar.totalDepositDue)} is due now in supplier deposits.`,
        `${fmtMoney(cashCalendar.totalBalanceDue)} is due later across ${cashCalendar.byTerms.map((t) => t.terms).join(", ")} terms.`,
      ]
    : ["No pending reorders — no near-term supplier cash commitments."];

  const actions = [];
  if (marketingRec) {
    actions.push(`Shift ~${fmtMoney(marketingRec.amount)}/week from ${marketingRec.from.name} to ${marketingRec.to.name} — ${marketingRec.note}`);
  }
  if (returnsRanking?.length) {
    const top = returnsRanking[0];
    actions.push(`${top.name} lost ${fmtMoney(top.returns)} to returns this period (${top.returnsPct}% of its revenue) — review sizing/fit before scaling its ad spend.`);
  }
  if (!actions.length) actions.push("No high-priority actions flagged this period.");

  return {
    store: store.name,
    rangeLabel,
    profitable,
    sections: [
      { title: "Financial position", lines: financial },
      { title: "Top risks", lines: risks },
      { title: "Cash position", lines: cash },
      { title: "Recommended actions", lines: actions },
    ],
  };
}

export function renderSummaryMarkdown(sum) {
  let out = `# ${sum.store} — Executive Summary\n\n_${sum.rangeLabel} · generated by Carter_\n\n`;
  for (const sec of sum.sections) {
    out += `## ${sec.title}\n\n`;
    for (const line of sec.lines) out += `- ${line}\n`;
    out += `\n`;
  }
  return out;
}
